/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "bound": "Порог отключения: -100.00 рублей",
    "Contract": "Договор №XXXXX",
    "contractInputCaption": "Номер договора",
    "Copytight": "© Илья Бураков 2012",
    "Done": "Done",
    "Hello, World Goodbye!": "Hello, World!",
    "Hello, World!": "Фамилия Имя Отчество",
    "LoginToAccount": "Вход в личный кабинет",
    "passwordInputCaption": "Пароль",
    "Text": "0 рублей",
    "Time Left": "Хватит на X дней",
    "usernameInputCaption": "0 рублей"
};



